artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/db483e19356a4d4ca556c4d80b654b22/artifacts
end_time: 1783272853402
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: db483e19356a4d4ca556c4d80b654b22
run_name: fcnn_bn
source_name: ''
source_type: 4
source_version: ''
start_time: 1783271736532
status: 3
tags: []
user_id: root
