artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/1ed1cd6720fa44988310558a0a08048d/artifacts
end_time: 1782826200029
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 1ed1cd6720fa44988310558a0a08048d
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782826151650
status: 3
tags: []
user_id: arch
