artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/c22479af809342e08622762285a8b1a5/artifacts
end_time: null
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: c22479af809342e08622762285a8b1a5
run_name: gradient_reversal_gan
source_name: ''
source_type: 4
source_version: ''
start_time: 1783092311238
status: 1
tags: []
user_id: root
