artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/647fc133d1a947aba0c5c1134ecc4689/artifacts
end_time: 1782816650929
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 647fc133d1a947aba0c5c1134ecc4689
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782816319205
status: 3
tags: []
user_id: arch
