artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/edab365185504484bf2c72aac60dad71/artifacts
end_time: 1783173760307
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: edab365185504484bf2c72aac60dad71
run_name: word2vec_long_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1783173691460
status: 3
tags: []
user_id: root
