artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/1b662a38d8e648679f1398cba18e3674/artifacts
end_time: 1783096815217
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 1b662a38d8e648679f1398cba18e3674
run_name: gradient_reversal_gan_long_run_1
source_name: ''
source_type: 4
source_version: ''
start_time: 1783096775891
status: 3
tags: []
user_id: root
