artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/59dc23e128154fb79e182d0880e3174b/artifacts
end_time: 1782820296091
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 59dc23e128154fb79e182d0880e3174b
run_name: two_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1782820278964
status: 3
tags: []
user_id: arch
