artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/f3fe477514854ed58bed0fef33ba5807/artifacts
end_time: 1782817047720
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: f3fe477514854ed58bed0fef33ba5807
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782817044844
status: 3
tags: []
user_id: arch
