artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/ef06c2b921444d85a89fd5b57c0cc7a5/artifacts
end_time: 1783173893744
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: ef06c2b921444d85a89fd5b57c0cc7a5
run_name: word2vec_hsoftmax_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1783173892238
status: 3
tags: []
user_id: root
