artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/636b9439d7f7496cb63e85b3e59c3984/artifacts
end_time: 1782828271330
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 636b9439d7f7496cb63e85b3e59c3984
run_name: three_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1782828254495
status: 3
tags: []
user_id: arch
