artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/e0c2536256c54c54ab7756f7413ba1b3/artifacts
end_time: 1782829177525
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: e0c2536256c54c54ab7756f7413ba1b3
run_name: 'three layer fcnn: stems'
source_name: ''
source_type: 4
source_version: ''
start_time: 1782828841815
status: 3
tags: []
user_id: arch
