artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/900bd37934ce4dea83d95f6a6eafb2e3/artifacts
end_time: 1782839095256
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 900bd37934ce4dea83d95f6a6eafb2e3
run_name: ReLU
source_name: ''
source_type: 4
source_version: ''
start_time: 1782838935889
status: 3
tags: []
user_id: arch
