artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/acdbe3f518bd405e8ae0ac691cdc3481/artifacts
end_time: 1783094811974
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: acdbe3f518bd405e8ae0ac691cdc3481
run_name: gradient_reversal_gan_long_run_1
source_name: ''
source_type: 4
source_version: ''
start_time: 1783094591200
status: 3
tags: []
user_id: root
