artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/3539faf2528c408bba9b7adf513e4876/artifacts
end_time: 1782828239587
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 3539faf2528c408bba9b7adf513e4876
run_name: one_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1782828225603
status: 3
tags: []
user_id: arch
