artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/f86f28f2d38e4ba0925cbeaa3819b611/artifacts
end_time: 1782811120576
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: f86f28f2d38e4ba0925cbeaa3819b611
run_name: one_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1782811098294
status: 3
tags: []
user_id: arch
