artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/821fb9520d2a446894b6efb6604d7027/artifacts
end_time: 1782811098293
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 821fb9520d2a446894b6efb6604d7027
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782811095482
status: 3
tags: []
user_id: arch
