artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/ff97349f32ec4cccbe893b3698681b53/artifacts
end_time: 1782813776498
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: ff97349f32ec4cccbe893b3698681b53
run_name: 'one_layer_fcnn: classifier weights'
source_name: ''
source_type: 4
source_version: ''
start_time: 1782813766618
status: 3
tags: []
user_id: arch
