artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/0ec87841aaec4e3e97d0e1f80f2adbfb/artifacts
end_time: 1782816319204
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 0ec87841aaec4e3e97d0e1f80f2adbfb
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782816290446
status: 3
tags: []
user_id: arch
