artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/2b5f16780fa946a5b6665fa2709e92ee/artifacts
end_time: 1783100492685
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 2b5f16780fa946a5b6665fa2709e92ee
run_name: gradient_reversal_gan
source_name: ''
source_type: 4
source_version: ''
start_time: 1783100479820
status: 3
tags: []
user_id: root
