artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/a3932a54fe7f4c3ba90f5d389b8a26ed/artifacts
end_time: 1783176674261
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: a3932a54fe7f4c3ba90f5d389b8a26ed
run_name: word2vec_hsoftmax_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1783176672783
status: 3
tags: []
user_id: root
