artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/490d0e62d0134e63809ab73252ceac72/artifacts
end_time: 1782985114879
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 490d0e62d0134e63809ab73252ceac72
run_name: two_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1782985090986
status: 3
tags: []
user_id: arch
