artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/129cdaa4a38c4ffb8d6cf3cc42f68cde/artifacts
end_time: 1782810620714
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 129cdaa4a38c4ffb8d6cf3cc42f68cde
run_name: one_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1782810599568
status: 3
tags: []
user_id: arch
