artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/6adbfca90434420d891b74777c2205f2/artifacts
end_time: 1782820188627
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 6adbfca90434420d891b74777c2205f2
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782820145305
status: 3
tags: []
user_id: arch
