artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/209b6c7caa0a493b9984935307d939d0/artifacts
end_time: null
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 209b6c7caa0a493b9984935307d939d0
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782807797882
status: 1
tags: []
user_id: arch
