artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/9108485654b94ffc96f45ce01c93a403/artifacts
end_time: 1782837072491
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 9108485654b94ffc96f45ce01c93a403
run_name: 'two layer fcnn: stems'
source_name: ''
source_type: 4
source_version: ''
start_time: 1782836640534
status: 3
tags: []
user_id: arch
