artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/247f826a7d6c492e9f628fcbe490e7ad/artifacts
end_time: 1782985074775
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 247f826a7d6c492e9f628fcbe490e7ad
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782985064399
status: 3
tags: []
user_id: arch
