artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/ad381c62353147a499c92912a33dc016/artifacts
end_time: null
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: ad381c62353147a499c92912a33dc016
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782810066219
status: 1
tags: []
user_id: arch
