artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/65f59d210aa742af8241310b4132cf5a/artifacts
end_time: 1782990561754
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 65f59d210aa742af8241310b4132cf5a
run_name: 'one_layer_fcnn: classifier weights'
source_name: ''
source_type: 4
source_version: ''
start_time: 1782990212269
status: 3
tags: []
user_id: root
