artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/187b05a734b14d9ba9cabe3d5cffa908/artifacts
end_time: 1782815455736
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 187b05a734b14d9ba9cabe3d5cffa908
run_name: three_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1782815439646
status: 3
tags: []
user_id: arch
