artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/725ee6fe66a243bf91e46f8d56ecfbba/artifacts
end_time: 1783175441924
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 725ee6fe66a243bf91e46f8d56ecfbba
run_name: word2vec_hsoftmax_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1783175440323
status: 3
tags: []
user_id: root
