artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/aa2dbe8cf8df44c0939ec04c44b20be1/artifacts
end_time: 1782831182334
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: aa2dbe8cf8df44c0939ec04c44b20be1
run_name: 'one_layer_fcnn: classifier weights'
source_name: ''
source_type: 4
source_version: ''
start_time: 1782830833735
status: 3
tags: []
user_id: arch
