artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/53594e883aef4250a4a1cce3cf7df729/artifacts
end_time: 1782815412209
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 53594e883aef4250a4a1cce3cf7df729
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782815403781
status: 3
tags: []
user_id: arch
