artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/87f81cfa135b4f9a8fe8a099d42fdfa6/artifacts
end_time: 1783181894068
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 87f81cfa135b4f9a8fe8a099d42fdfa6
run_name: 'two layer fcnn: stems'
source_name: ''
source_type: 4
source_version: ''
start_time: 1783180523269
status: 3
tags: []
user_id: root
