artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/2a9a810720514beaaebae3ee6d8668ac/artifacts
end_time: 1783099952802
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 2a9a810720514beaaebae3ee6d8668ac
run_name: gradient_reversal_gan_long_run_1
source_name: ''
source_type: 4
source_version: ''
start_time: 1783099946189
status: 3
tags: []
user_id: root
