artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/b7820dac42e447e2b2a1818893f2ee4a/artifacts
end_time: 1783099861904
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: b7820dac42e447e2b2a1818893f2ee4a
run_name: gradient_reversal_gan_long_run_1
source_name: ''
source_type: 4
source_version: ''
start_time: 1783099726313
status: 3
tags: []
user_id: root
