artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/7cf1d5126a79420fa55a6753ecf3df9c/artifacts
end_time: 1783099524608
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 7cf1d5126a79420fa55a6753ecf3df9c
run_name: gradient_reversal_gan_long_run_1
source_name: ''
source_type: 4
source_version: ''
start_time: 1783099133994
status: 3
tags: []
user_id: root
