artifact_uri: file:///home/arch/scripts/neural-networks-fundamentals/.laborantum/mlflow_logs/665985386370026847/8be8c8b79f044887930c706926832be3/artifacts
end_time: null
entry_point_name: ''
experiment_id: '665985386370026847'
lifecycle_stage: active
run_id: 8be8c8b79f044887930c706926832be3
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782816675934
status: 1
tags: []
user_id: arch
